# Default values for arch-delugevpn.

replicaCount: 1

image:
  repository: binhex/arch-delugevpn
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

vpn:
  enabled: "yes"
  user: ""
  password: ""
  provider: ""
  client: ""
  options: ""

strictPortForward: "no"

enablePrivoxy: "no"

lanNetwork: ""

nameServers: ""

deluge:
  daemonLogLevel: "warning"
  webLogLevel: "warning"

additionalPorts: ""

debug: false

umask: 000
puid: 0
pgid: 0
