apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  VPN_ENABLED: {{ .Values.vpn.enabled }}
  VPN_USER: {{ .Values.vpn.user }}
{{- if .Values.vpn.password }}
  VPN_PASS: {{ .Values.vpn.password }}
{{- end }}
{{- if .Values.vpn.provider }}
  VPN_PROV: {{ .Values.vpn.provider }}
{{- end }}
{{- if .Values.vpn.client }}
  VPN_CLIENT: {{ .Values.vpn.client }}
{{- end }}
{{- if .Values.vpn.options }}
  VPN_OPTIONS: {{ .Values.vpn.options }}
{{- end }}
  # STRICT_PORT_FORWARD: {{ .Values.strictPortForward }}
  # ENABLE_PRIVOXY: {{ .Values.enablePrivoxy }}
  # LAN_NETWORK: {{ .Values.lanNetwork }}
  # NAME_SERVERS: {{ .Values.nameServers }}
  # DELUGE_DAEMON_LOG_LEVEL: {{ .Values.deluge.daemonLogLevel }}
  # DELUGE_WEB_LOG_LEVEL: {{ .Values.deluge.webLogLevel }}
  # ADDITIONAL_PORTS: {{ .Values.additionalPorts }}
  # DEBUG: {{ .Values.debug }}
  # UMASK: {{ .Values.umask }}
  # PUID: {{ .Values.puid }}
  # PGID: {{ .Values.pgid }}
