apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
{{- with .Values }}
  VPN_ENABLED: {{ .vpn.enabled }}
{{- if .vpn.enabled }}
  VPN_USER: {{ required "A valid username is required!" .vpn.user }}
  VPN_PASS: {{ required "A valid password is required!" .vpn.password }}
  VPN_PROV: {{ required "A valid VPN provider is required!" .vpn.provider }}
  VPN_CLIENT: {{ required "A valid VPN client is required!" .vpn.client }}
  {{- if .vpn.options }}
  VPN_OPTIONS: {{ .vpn.options }}
  {{- end }}
{{- end }}
  STRICT_PORT_FORWARD: {{ .strictPortForward }}
  ENABLE_PRIVOXY: {{ .enablePrivoxy }}
{{- if .lanNetwork }}
  LAN_NETWORK: {{ .lanNetwork }}
{{- end }}
{{- if .nameServers }}
  NAME_SERVERS: {{ .nameServers }}
{{- end }}
  DELUGE_DAEMON_LOG_LEVEL: {{ .deluge.daemonLogLevel }}
  DELUGE_WEB_LOG_LEVEL: {{ .deluge.webLogLevel }}
{{- if .additionalPorts }}
  ADDITIONAL_PORTS: {{ .additionalPorts }}
{{- end }}
  DEBUG: {{ .debug }}
  UMASK: {{ .umask }}
  PUID: {{ .puid }}
  PGID: {{ .pgid }}
{{- end }}
